---

- name: Ensure PasswordAuthentication setting
  ansible.builtin.lineinfile:
    path:          /etc/ssh/sshd_config
    backup:        true
    search_string: 'PasswordAuthentication'
    line:          "PasswordAuthentication {{ sshd_passwordauthentication }}"
  notify: restart sshd

- name: Ensure /etc/ssh/trusted-user-ca-keys.pem
  ansible.builtin.copy:
    dest: /etc/ssh/trusted-user-ca-keys.pem
    content: "{{ sshd_trusted_user_ca_keys }}"
    mode: "u+rw,g-wx,o-rwx"
  when: sshd_trusted_user_ca_keys is defined and sshd_trusted_user_ca_keys

- name: Ensure TrustedUserCAKeys in /etc/ssh/sshd_config
  ansible.builtin.lineinfile:
    path:          /etc/ssh/sshd_config
    backup:        true
    line:          TrustedUserCAKeys /etc/ssh/trusted-user-ca-keys.pem
  when:   sshd_trusted_user_ca_keys is defined and sshd_trusted_user_ca_keys
  notify: restart sshd

- name: Ensure remove /root/.ssh/authorized_keys
  ansible.builtin.file:
    path:  /root/.ssh/authorized_keys
    state: absent
  when: sshd_remove_authorized_keys

- name: Ensure no includes in /etc/ssh/sshd_config
  ansible.builtin.lineinfile:
    path:   /etc/ssh/sshd_config
    backup: true
    regexp: '^\s*Include'
    state:  absent
  when:   sshd_no_includes
  notify: restart sshd


...
